# Generated by Django 4.2.3 on 2023-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='integer',
            field=models.IntegerField(null=True),
        ),
    ]
