# Generated by Django 4.2.3 on 2023-08-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_id',
        ),
    ]
