# Generated by Django 4.2.3 on 2023-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
