# Generated by Django 4.2.3 on 2023-07-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0003_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
