# Generated by Django 4.2.3 on 2023-08-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_discount',
        ),
    ]
