# Generated by Django 4.2.3 on 2023-08-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0007_remove_profile_image_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='string',
        ),
    ]
