# Generated by Django 4.2.3 on 2023-08-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0009_alter_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
