# Generated by Django 4.2.3 on 2023-08-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0010_remove_review_name_remove_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
