# Generated by Django 4.2.3 on 2023-08-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0012_orders_user_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='eshopas_app.product'),
        ),
    ]
