# Generated by Django 4.2.3 on 2023-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0015_remove_product_favourites_product_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='home_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city_town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
