# Generated by Django 4.2.3 on 2023-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0016_rename_address_profile_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city_town',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
