# Generated by Django 4.2.3 on 2023-08-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0017_remove_profile_city_town_remove_profile_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
