# Generated by Django 4.2.3 on 2023-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0018_profile_home_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='city_town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
