# Generated by Django 4.2.3 on 2023-08-04 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshopas_app', '0020_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_profile_pics'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
